import mongoose, { Schema } from "mongoose";
import mongooseAggregatePaginate from "mongoose-aggregate-paginate-v2";

const videoSchema = new Schema(
    {
        videoFile: {
            url: { type: String, required: [true, "Video file URL is required"] },
            public_id: { type: String, required: true } // For Cloudinary deletion
        },
        thumbnail: {
            url: { type: String, required: [true, "Thumbnail URL is required"] },
            public_id: { type: String, default: null }, // Null for auto-generated thumbnails
            isAutoGenerated: { type: Boolean, default: false } // Track if thumbnail was auto-generated
        },
        title: {
            type: String,
            required: [true, "Title is required"],
            trim: true
        },
        description: {
            type: String,
            default: "", // Optional - AI can generate if empty
            trim: true
        },
        duration: {
            type: Number, 
            required: [true, "Duration is required"]
        },
        views: {
            type: Number,
            default: 0
        },
        transcript: {
            type: String, 
            default: ""
        },
        tags: {
            type: [String],
            default: [],
            index: true 
        },
        isPublished: {
            type: Boolean,
            default: true
        },
        // --- StreamWire Identity & Stealth ---
        isStealthMode: {
            type: Boolean,
            default: false // Allows retroactive masking of the creator's identity
        },
        // --- Engagement Features ---
        // Array of pinned comments. Latest pins can be managed by controller logic ($position: 0)
        pinnedComments: [
            {
                type: Schema.Types.ObjectId,
                ref: "Comment"
            }
        ],
        owner: {
            type: Schema.Types.ObjectId,
            ref: "User",
            required: true
        },
        // 🔥 Trend Score - Calculated periodically or on engagement
        trendScore: {
            type: Number,
            default: 0,
            index: true // For fast trending queries
        }
    },
    { timestamps: true }
);

// Plugin for advanced pagination in aggregation pipelines
videoSchema.plugin(mongooseAggregatePaginate);

// --- SEARCH ENGINE OPTIMIZATION ---
// Weights allow title matches to rank higher than description matches
videoSchema.index(
    { 
        title: "text", 
        tags: "text",  
        description: "text",
        transcript: "text" 
    },
    {
        weights: {
            title: 10,      
            tags: 8,       
            description: 5,  
            transcript: 1    
        },
        name: "VideoTextIndex"
    }
);

// --- PERFORMANCE INDEXES ---
videoSchema.index({ owner: 1 });
videoSchema.index({ isPublished: 1 });
videoSchema.index({ isStealthMode: 1 }); // For the dedicated Stealth Feed
videoSchema.index({ views: -1 });        // For "Most Viewed" sorting
videoSchema.index({ createdAt: -1 });    // For "Latest Videos" sorting
videoSchema.index({ pinnedComments: 1 }); // Quick lookup for pinned interactions
videoSchema.index({ trendScore: -1 });   // For "Trending" sorting

export const Video = mongoose.model("Video", videoSchema);